INSERT INTO bears(id, name, age, gender, color, temperament)
VALUES(1, "Mr.Chocolate", 20, "M", "Black", "Angry")
VALUES(1, "Rowdy", 20, "M", "Black", "Angry")
VALUES(1, "Tabitha", 20, "F", "Black", "Angry")
VALUES(1, "Sergeant Brown", 20, "M", "Black", "Angry")
VALUES(1, "Melissa", 20, "F", "Black", "Angry")
VALUES(1, "Grinch", 20, "M", "Black", "Angry")
VALUES(1, "Wendy", 20, "F", "Black", "Angry")
VALUES(1, "Unnamed", 20, "M", "Black", "Angry")